# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'

gem 'awesome_print'

gem 'faker'

gem 'pg'

# gem 'rubocop'

gem 'progressbar'

# gem 'benchmark'

gem 'colorize'

# gem 'pg_search'
