# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'

gem 'awesome_print'

gem 'faker'

gem 'pg', '~> 1.5'

gem 'rubocop', '~> 1.63'

gem 'progressbar'

gem 'benchmark'

gem 'colorize'
