require 'active_record'

task default: :instructions

task :instructions do
  sh 'rake -T'
end

desc 'create postgres db in docker'
task :install_pg do
  sh <<~SHELL
    docker run --name demystifying-postgres \
    -e POSTGRES_PASSWORD=password \
    -e POSTGRES_USER=$(whoami) \
    -e POSTGRES_DB=index_test \
    -p 5432:5432 \
    -d postgres
  SHELL
end

desc 'Run the app'
task :run do
  sh 'bundle exec ruby app.rb'
end

desc 'connect via psql'
task :psql do
  sh 'psql -h localhost -p 5432 -U friendlyantz -d index_test'
end
